/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ansexp.forms;

import ansexp.*;
import ansexp.calculator.DefaultCalculator;
import java.awt.Label;
import java.io.File;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
 import java.util.zip.*;

/**
 *
 * @author eremeykin
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
//        jTabbedPane1.setTabComponentAt(0, new ButtonTabComponent(jTabbedPane1));
//        ButtonTabComponent btc = new ButtonTabComponent(new JTabbedPane());
//        this.add(btc);
//        try {
//            SQLiteJDBC.getInstance().setSourceFile(new File("C:\\Users\\Пётр\\Desktop\\Курсовой\\Код\\Код\\AnsExp\\src\\database\\mainDB.sqlite"));
//        } catch (ClassNotFoundException | SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Произошла ошибка БД."
//                    + "Файл не может быть открыт");
//            JOptionPane.showMessageDialog(this, ex);
//        }
//        try {
//            XMLParser parser = XMLParser.getInstance(new File("C:\\Users\\Пётр\\Desktop\\Курсовой\\Код\\Код\\AnsExp\\src\\XML\\model2.xml"));
//            outline1 = new OutlineCreator(parser.getResultNode()).getOutline();
//            jScrollPane1.setViewportView(outline1);
//            jTabbedPane1.setTitleAt(0, "model1");
//        } catch (XMLParser.XMLParsingException exc) {
//            JOptionPane.showMessageDialog(this, "Произошла ошибка при чтении XML файла."
//                    + "Файл не может быть открыт");
//            JOptionPane.showMessageDialog(this, exc);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Произошла ошибка работе с БД.");
//            JOptionPane.showMessageDialog(this, ex);
//        } catch (SQLiteJDBC.UndefinedDBFile ex) {
//            JOptionPane.showMessageDialog(this, "База данных не определена.\n Выбирете БД вручную");
//            JFileChooser fileChooser = new JFileChooser();
//            int res = fileChooser.showDialog(jMenu1, "Открыть модель");
//            if (res == JFileChooser.APPROVE_OPTION) {
//                try {
//                    SQLiteJDBC.getInstance().setSourceFile(fileChooser.getSelectedFile());
//                } catch (ClassNotFoundException | SQLException e) {
//                    JOptionPane.showMessageDialog(this, "Не удается открыть БД. Программа будет закрыта");
//                    System.exit(-1);
//
//                }
//            }
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        outline1 = new org.netbeans.swing.outline.Outline();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(outline1);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Выбрать файл");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Новая вкладка");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Выход");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int res = fileChooser.showDialog(jMenu1, "Открыть модель");
        if (res == JFileChooser.APPROVE_OPTION) {
            try {
                XMLParser parser = XMLParser.getInstance(fileChooser.getSelectedFile());
                outline1 = new OutlineCreator(parser.getResultNode()).getOutline();
                jScrollPane1.setViewportView(outline1);
            } catch (XMLParser.XMLParsingException exc) {
                JOptionPane.showMessageDialog(this, "Произошла ошибка при чтении XML файла."
                        + "Файл не может быть открыт");
                JOptionPane.showMessageDialog(this, exc);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Произошла ошибка работе с БД.");
                JOptionPane.showMessageDialog(this, ex);
            } catch (SQLiteJDBC.UndefinedDBFile ex) {
                JOptionPane.showMessageDialog(this, "База данных не определена.\n Выбирете БД вручную");
                JFileChooser fileChooser2 = new JFileChooser();
                int res2 = fileChooser2.showDialog(jMenu1, "Открыть модель");
                if (res2 == JFileChooser.APPROVE_OPTION) {
                    try {
                        SQLiteJDBC.getInstance().setSourceFile(fileChooser.getSelectedFile());
                    } catch (ClassNotFoundException | SQLException e) {
                        JOptionPane.showMessageDialog(this, "Не удается открыть БД. Программа будет закрыта");
                        System.exit(-1);

                    }
                }
            }
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.add(new Label("label1"));
        jTabbedPane1.setTabComponentAt(jTabbedPane1.getTabCount()-1, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.netbeans.swing.outline.Outline outline1;
    // End of variables declaration//GEN-END:variables
}
